package constants

const (
	ApiPrefix               string = "/api"
	ApiVersion              uint8  = 1
	Server                  string = "http://localhost:8080/"
	HeaderAuthorization     string = "Authorization"
	BearerPrefix            string = "Bearer"
	EnvJwtSecret            string = "JWT_SECRET"
	UserID                  string = "UserID"
	UserRole                string = "userRole"
	SessionID               string = "sessionID"
	DbHost                  string = "DB_HOST"
	DbUser                  string = "DB_USER"
	DbPassword              string = "DB_PASSWORD"
	DbName                  string = "DB_NAME"
	DbPort                  string = "DB_PORT"
	DateFormat              string = "2006-01-02"
	Port                    string = "PORT"
	LoginFailed             string = "LOGIN_FAILED"
	LoginSuccess            string = "LOGIN_SUCCESS"
	LoginSuccessful         string = "You have successfully logged in"
	MaxLoginAttempts        string = "MAX_LOGIN_ATTEMPTS"
	AccountLocked           string = "ACCOUNT_LOCKED"
	ToManyRequest           string = "Too many failed login attempts"
	WrongPassword           string = "WRONG_PASSWORD"
	RefreshTokenTtlDays     string = "REFRESH_TOKEN_TTL_DAYS"
	JwtTtlMinutes           string = "JWT_TTL_MINUTES"
	TokenRefreshed          string = "TOKEN_REFRESHED"
	TokenRefreshedDetail    string = "Access token refreshed successfully"
	ForgotPasswordRequested string = "FORGOT_PASSWORD_REQUESTED"
	ResetPasswordDetail     string = "Password reset requested"
	PasswordResetSuccess    string = "PASSWORD_RESET_SUCCESS"
	ChangePasswordDetail    string = "Password updated successfully"
	Token                   string = "token"
)
